<a href="https://colab.research.google.com/github/Chinmaya54/CP_02_T16_MineCrafters/blob/Asish/Data_Mininig_Project_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing necessary libraries


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report, precision_score, recall_score, f1_score
df = pd.read_csv("/content/cleaned_data1.csv")

Label encoding the language

In [3]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['lang_encoded'] = label_encoder.fit_transform(df['lang'])

In [28]:
df

authors  bestsellers-rank  \
0               1           49848.0   
1            2, 3          115215.0   
2               4           11732.0   
3      5, 6, 7, 8          114379.0   
4               9           98413.0   
...           ...               ...   
27324       28253          701883.0   
27325       28254          926336.0   
27326       28255          741018.0   
27327       28256          934272.0   
27328       28257          684639.0   

                                        categories  \
0      214, 220, 237, 2646, 2647, 2659, 2660, 2679   
1                                        235, 3386   
2                             358, 2630, 360, 2632   
3                                  377, 2978, 2980   
4                                       2813, 2980   
...                                            ...   
27324                        163, 3278, 2649, 1530   
27325                                   1532, 1562   
27326                 1530, 1531, 1719, 1755, 1766   
27327                                   1520, 1521   
27328            386, 3388, 1520, 1667, 1682, 1683   

                                             description  dimension-x  \
0      SOLDIER FIVE is an elite soldier's explosive m...        129.0   
1      John Moran and Carl Williams were the two bigg...        127.0   
2      Sir Phillip knew that Eloise Bridgerton was a ...        150.0   
3      The Third Book of General Ignorance  gathers t...        153.0   
4      The Try Guys deliver their first book-an inspi...        191.0   
...                                                  ...          ...   
27324  This volume explores the development of the ea...        156.0   
27325  To those of us who are not mathematicians or p...        152.0   
27326  Like many apparently simple devices, the verti...        152.0   
27327  Debate over the nature of science has recently...        153.0   
27328  Writers know only too well how long it can tak...        139.0   

       dimension-y  dimension-z      edition    edition-statement for-ages  \
0            198.0        20.00          NaN                  NaN      NaN   
1            203.2        25.40          NaN                  NaN      NaN   
2            224.0        28.00  New edition                  NaN      NaN   
3            234.0        24.00          NaN  Export - Airside ed      NaN   
4            240.0        29.00          NaN                  NaN      NaN   
...            ...          ...          ...                  ...      ...   
27324        235.0        20.83  New edition          New edition      NaN   
27325        229.0        13.00          NaN                  NaN      NaN   
27326        229.0        27.43          NaN          Revised ed.      NaN   
27327        227.0        21.00  New edition          New edition      NaN   
27328        217.0        19.00          NaN              2nd ed.      NaN   

       format                       imprint lang  publication-date  \
0         1.0         Mainstream Publishing   en  14-10-2004 00:00   
1         1.0                           NaN   en  13-03-2009 00:00   
2         1.0                           NaN   es  30-04-2020 00:00   
3         1.0                           NaN   en  01-10-2015 00:00   
4         2.0  HarperCollins Publishers Ltd   en  18-06-2019 00:00   
...       ...                           ...  ...               ...   
27324     1.0                           NaN   en  30-09-2002 00:00   
27325     1.0                           NaN   en  01-03-2011 00:00   
27326     1.0                           NaN   en  01-01-2003 00:00   
27327     1.0   University of Chicago Press   en  15-05-1990 00:00   
27328     1.0                           NaN  NaN               NaN   

       publication-place  rating-avg  rating-count  \
0                    NaN        4.03         292.0   
1                    NaN        3.60         335.0   
2                    NaN        3.88       37211.0   
3                    

In [4]:
df['weight']=df['weight']//100

In [30]:
df

authors  bestsellers-rank  \
0               1           49848.0   
1            2, 3          115215.0   
2               4           11732.0   
3      5, 6, 7, 8          114379.0   
4               9           98413.0   
...           ...               ...   
27324       28253          701883.0   
27325       28254          926336.0   
27326       28255          741018.0   
27327       28256          934272.0   
27328       28257          684639.0   

                                        categories  \
0      214, 220, 237, 2646, 2647, 2659, 2660, 2679   
1                                        235, 3386   
2                             358, 2630, 360, 2632   
3                                  377, 2978, 2980   
4                                       2813, 2980   
...                                            ...   
27324                        163, 3278, 2649, 1530   
27325                                   1532, 1562   
27326                 1530, 1531, 1719, 1755, 1766   
27327                                   1520, 1521   
27328            386, 3388, 1520, 1667, 1682, 1683   

                                             description  dimension-x  \
0      SOLDIER FIVE is an elite soldier's explosive m...        129.0   
1      John Moran and Carl Williams were the two bigg...        127.0   
2      Sir Phillip knew that Eloise Bridgerton was a ...        150.0   
3      The Third Book of General Ignorance  gathers t...        153.0   
4      The Try Guys deliver their first book-an inspi...        191.0   
...                                                  ...          ...   
27324  This volume explores the development of the ea...        156.0   
27325  To those of us who are not mathematicians or p...        152.0   
27326  Like many apparently simple devices, the verti...        152.0   
27327  Debate over the nature of science has recently...        153.0   
27328  Writers know only too well how long it can tak...        139.0   

       dimension-y  dimension-z      edition    edition-statement for-ages  \
0            198.0        20.00          NaN                  NaN      NaN   
1            203.2        25.40          NaN                  NaN      NaN   
2            224.0        28.00  New edition                  NaN      NaN   
3            234.0        24.00          NaN  Export - Airside ed      NaN   
4            240.0        29.00          NaN                  NaN      NaN   
...            ...          ...          ...                  ...      ...   
27324        235.0        20.83  New edition          New edition      NaN   
27325        229.0        13.00          NaN                  NaN      NaN   
27326        229.0        27.43          NaN          Revised ed.      NaN   
27327        227.0        21.00  New edition          New edition      NaN   
27328        217.0        19.00          NaN              2nd ed.      NaN   

       format                       imprint lang  publication-date  \
0         1.0         Mainstream Publishing   en  14-10-2004 00:00   
1         1.0                           NaN   en  13-03-2009 00:00   
2         1.0                           NaN   es  30-04-2020 00:00   
3         1.0                           NaN   en  01-10-2015 00:00   
4         2.0  HarperCollins Publishers Ltd   en  18-06-2019 00:00   
...       ...                           ...  ...               ...   
27324     1.0                           NaN   en  30-09-2002 00:00   
27325     1.0                           NaN   en  01-03-2011 00:00   
27326     1.0                           NaN   en  01-01-2003 00:00   
27327     1.0   University of Chicago Press   en  15-05-1990 00:00   
27328     1.0                           NaN  NaN               NaN   

       publication-place  rating-avg  rating-count  \
0                    NaN        4.03         292.0   
1                    NaN        3.60         335.0   
2                    NaN        3.88       37211.0   
3                    

In [5]:
df['rating-class'] = pd.cut(df['rating-avg'], bins=[0, 2, 3, 5], labels=['Low', 'Medium', 'High'], include_lowest=True)

In [6]:
df['rating-class'] = pd.cut(df['rating-avg'], bins=[0, 2, 3, 5], labels=['Low', 'Medium', 'High'], include_lowest=True)
val=[ 'bestsellers-rank', 'lang_encoded','dimension-x', 'dimension-y', 'dimension-z','rating-count', 'weight']
X=df[val]
y = df['rating-class']

Dealing with null values of X and y


In [7]:
from sklearn.impute import SimpleImputer
# Handle NaN values in X (input features)
X_imputer = SimpleImputer(strategy='mean')  # You can use 'mean', 'median', or other strategies
X_imputed = X_imputer.fit_transform(X)
X = pd.DataFrame(X_imputed, columns=X.columns)
# Handle NaN values in y (target variable)
y_imputer = SimpleImputer(strategy='most_frequent')  # Replace NaNs with the most frequent class
y_imputed = y_imputer.fit_transform(y.values.reshape(-1, 1))
y = pd.Series(y_imputed.flatten())

Random Forest

In [48]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, y_train)

y_test_pred = classifier.predict(X_test)

confusion_test = confusion_matrix(y_test, y_test_pred)
report_test = classification_report(y_test, y_test_pred)
accuracy_test = accuracy_score(y_test, y_test_pred)

print("Confusion Matrix (Test Set):\n", confusion_test)
print("Classification Report (Test Set):\n", report_test)
print("Accuracy Score (Test Set):", accuracy_test)

y_val_pred = classifier.predict(X_val)

confusion_val = confusion_matrix(y_val, y_val_pred)
report_val = classification_report(y_val, y_val_pred)
accuracy_val = accuracy_score(y_val, y_val_pred)

print("Confusion Matrix (Validation Set):\n", confusion_val)
print("Classification Report (Validation Set):\n", report_val)
print("Accuracy Score (Validation Set):", accuracy_val)



Confusion Matrix (Test Set):
 [[1719    0    8]
 [  11    0    2]
 [  79    1    2]]
Classification Report (Test Set):
               precision    recall  f1-score   support

        High       0.95      1.00      0.97      1727
         Low       0.00      0.00      0.00        13
      Medium       0.17      0.02      0.04        82

    accuracy                           0.94      1822
   macro avg       0.37      0.34      0.34      1822
weighted avg       0.91      0.94      0.92      1822

Accuracy Score (Test Set): 0.9445664105378705
Confusion Matrix (Validation Set):
 [[1701    1   12]
 [  22    1    0]
 [  83    2    1]]
Classification Report (Validation Set):
               precision    recall  f1-score   support

        High       0.94      0.99      0.97      1714
         Low       0.25      0.04      0.07        23
      Medium       0.08      0.01      0.02        86

    accuracy                           0.93      1823
   macro avg       0.42      0.35      0.35      

Logistic Regression

In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Create and train the Logistic Regression model
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred = logistic_regression.predict(X_val)
y_test_pred = logistic_regression.predict(X_test)

# Calculate confusion matrix for validation set
conf_matrix_val = confusion_matrix(y_val, y_val_pred)
print("Confusion Matrix (Validation Set):")
print(conf_matrix_val)


# Calculate accuracy for validation set
accuracy_val = accuracy_score(y_val, y_val_pred)
print("Accuracy (Validation Set):", accuracy_val)

class_report_val = classification_report(y_val, y_val_pred)
print("Classification Report (Validation Set):")
print(class_report_val)


# Calculate confusion matrix for test set
conf_matrix_test = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix (Test Set):")
print(conf_matrix_test)

# Calculate accuracy for test set
accuracy_test = accuracy_score(y_test, y_test_pred)
print("Accuracy (Test Set):", accuracy_test)

class_report_test = classification_report(y_test, y_test_pred)
print("Classification Report (Test Set):")
print(class_report_test)



Confusion Matrix (Validation Set):
[[1713    1    0]
 [  23    0    0]
 [  86    0    0]]
Accuracy (Validation Set): 0.9396599012616567
Classification Report (Validation Set):
              precision    recall  f1-score   support

        High       0.94      1.00      0.97      1714
         Low       0.00      0.00      0.00        23
      Medium       0.00      0.00      0.00        86

    accuracy                           0.94      1823
   macro avg       0.31      0.33      0.32      1823
weighted avg       0.88      0.94      0.91      1823

Confusion Matrix (Test Set):
[[1727    0    0]
 [  13    0    0]
 [  82    0    0]]
Accuracy (Test Set): 0.9478594950603733
Classification Report (Test Set):
              precision    recall  f1-score   support

        High       0.95      1.00      0.97      1727
         Low       0.00      0.00      0.00        13
      Medium       0.00      0.00      0.00        82

    accuracy                           0.95      1822
   macro avg 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

Support vector functtion

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Split the existing data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an SVM classifier
svm_classifier = SVC(kernel='linear', C=1, random_state=42)

# Train the SVM classifier on the training set
svm_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_test_pred_svm = svm_classifier.predict(X_test)

# Calculate the confusion matrix for the test set
confusion_matrix_test_svm = confusion_matrix(y_test, y_test_pred_svm)
print("Confusion Matrix (Test Set - SVM):")
print(confusion_matrix_test_svm)

# Calculate the accuracy for the test set
accuracy_test_svm = accuracy_score(y_test, y_test_pred_svm)
print("Accuracy (Test Set - SVM):", accuracy_test_svm)

# Generate a classification report for the test set
class_report_test_svm = classification_report(y_test, y_test_pred_svm)
print("Classification Report (Test Set - SVM):")
print(class_report_test_svm)


KNN algorithm

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Split the existing data into train, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Create a KNN classifier with a specified number of neighbors (e.g., n_neighbors=5)
knn_classifier = KNeighborsClassifier(n_neighbors=5)

# Train the KNN classifier on the training set
knn_classifier.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred_knn = knn_classifier.predict(X_val)

# Make predictions on the test set
y_test_pred_knn = knn_classifier.predict(X_test)

# Calculate the accuracy for the validation set
accuracy_val_knn = accuracy_score(y_val, y_val_pred_knn)
print("Accuracy (Validation Set - KNN):", accuracy_val_knn)

# Calculate the accuracy for the test set
accuracy_test_knn = accuracy_score(y_test, y_test_pred_knn)
print("Accuracy (Test Set - KNN):", accuracy_test_knn)

# Generate a classification report for the validation set
class_report_val_knn = classification_report(y_val, y_val_pred_knn)
print("Classification Report (Validation Set - KNN):")
print(class_report_val_knn)

# Generate a classification report for the test set
class_report_test_knn = classification_report(y_test, y_test_pred_knn)
print("Classification Report (Test Set - KNN):")
print(class_report_test_knn)


Accuracy (Validation Set - KNN): 0.9560868504513296
Accuracy (Test Set - KNN): 0.9578048780487805
Classification Report (Validation Set - KNN):
              precision    recall  f1-score   support

        High       0.96      0.99      0.98      3937
         Low       0.00      0.00      0.00        31
      Medium       0.10      0.02      0.03       131

    accuracy                           0.96      4099
   macro avg       0.35      0.34      0.33      4099
weighted avg       0.93      0.96      0.94      4099

Classification Report (Test Set - KNN):
              precision    recall  f1-score   support

        High       0.96      1.00      0.98      3931
         Low       1.00      0.03      0.05        36
      Medium       0.37      0.05      0.09       133

    accuracy                           0.96      4100
   macro avg       0.78      0.36      0.37      4100
weighted avg       0.94      0.96      0.94      4100



In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Split the existing data into train, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Create an SVM classifier with a specified kernel (e.g., kernel='linear')
svm_classifier = SVC(kernel='linear', random_state=42)

# Train the SVM classifier on the training set
svm_classifier.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred_svm = svm_classifier.predict(X_val)

# Make predictions on the test set
y_test_pred_svm = svm_classifier.predict(X_test)

# Calculate the accuracy for the validation set
accuracy_val_svm = accuracy_score(y_val, y_val_pred_svm)
print("Accuracy (Validation Set - SVM):", accuracy_val_svm)

# Calculate the accuracy for the test set
accuracy_test_svm = accuracy_score(y_test, y_test_pred_svm)
print("Accuracy (Test Set - SVM):", accuracy_test_svm)

# Generate a classification report for the validation set
class_report_val_svm = classification_report(y_val, y_val_pred_svm)
print("Classification Report (Validation Set - SVM):")
print(class_report_val_svm)

# Generate a classification report for the test set
class_report_test_svm = classification_report(y_test, y_test_pred_svm)
print("Classification Report (Test Set - SVM):")
print(class_report_test_svm)


Naive-Bayes

In [8]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Split the existing data into train, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Create a Naive Bayes classifier (Gaussian Naive Bayes)
naive_bayes_classifier = GaussianNB()

# Train the Naive Bayes classifier on the training set
naive_bayes_classifier.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred_nb = naive_bayes_classifier.predict(X_val)

# Make predictions on the test set
y_test_pred_nb = naive_bayes_classifier.predict(X_test)

# Calculate the accuracy for the validation set
accuracy_val_nb = accuracy_score(y_val, y_val_pred_nb)
print("Accuracy (Validation Set - Naive Bayes):", accuracy_val_nb)

# Calculate the accuracy for the test set
accuracy_test_nb = accuracy_score(y_test, y_test_pred_nb)
print("Accuracy (Test Set - Naive Bayes):", accuracy_test_nb)

# Generate a classification report for the validation set
class_report_val_nb = classification_report(y_val, y_val_pred_nb)
print("Classification Report (Validation Set - Naive Bayes):")
print(class_report_val_nb)

# Generate a classification report for the test set
class_report_test_nb = classification_report(y_test, y_test_pred_nb)
print("Classification Report (Test Set - Naive Bayes):")
print(class_report_test_nb)


Accuracy (Validation Set - Naive Bayes): 0.4806050256160039
Accuracy (Test Set - Naive Bayes): 0.4870731707317073
Classification Report (Validation Set - Naive Bayes):
              precision    recall  f1-score   support

        High       1.00      0.49      0.66      3937
         Low       0.02      0.97      0.04        31
      Medium       0.01      0.03      0.01       131

    accuracy                           0.48      4099
   macro avg       0.34      0.50      0.24      4099
weighted avg       0.96      0.48      0.63      4099

Classification Report (Test Set - Naive Bayes):
              precision    recall  f1-score   support

        High       1.00      0.50      0.66      3931
         Low       0.03      1.00      0.05        36
      Medium       0.01      0.04      0.01       133

    accuracy                           0.49      4100
   macro avg       0.34      0.51      0.24      4100
weighted avg       0.96      0.49      0.64      4100



Gradient Boosting Algorithm

In [9]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Split the existing data into train, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Create a Gradient Boosting classifier
gb_classifier = GradientBoostingClassifier(n_estimators=100, random_state=42)

# Train the Gradient Boosting classifier on the training set
gb_classifier.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred_gb = gb_classifier.predict(X_val)

# Make predictions on the test set
y_test_pred_gb = gb_classifier.predict(X_test)

# Calculate the accuracy for the validation set
accuracy_val_gb = accuracy_score(y_val, y_val_pred_gb)
print("Accuracy (Validation Set - Gradient Boosting):", accuracy_val_gb)

# Calculate the accuracy for the test set
accuracy_test_gb = accuracy_score(y_test, y_test_pred_gb)
print("Accuracy (Test Set - Gradient Boosting):", accuracy_test_gb)

# Generate a classification report for the validation set
class_report_val_gb = classification_report(y_val, y_val_pred_gb)
print("Classification Report (Validation Set - Gradient Boosting):")
print(class_report_val_gb)

# Generate a classification report for the test set
class_report_test_gb = classification_report(y_test, y_test_pred_gb)
print("Classification Report (Test Set - Gradient Boosting):")
print(class_report_test_gb)


Accuracy (Validation Set - Gradient Boosting): 0.9602342034642596
Accuracy (Test Set - Gradient Boosting): 0.9580487804878048
Classification Report (Validation Set - Gradient Boosting):
              precision    recall  f1-score   support

        High       0.96      1.00      0.98      3937
         Low       0.00      0.00      0.00        31
      Medium       0.00      0.00      0.00       131

    accuracy                           0.96      4099
   macro avg       0.32      0.33      0.33      4099
weighted avg       0.92      0.96      0.94      4099

Classification Report (Test Set - Gradient Boosting):
              precision    recall  f1-score   support

        High       0.96      1.00      0.98      3931
         Low       0.25      0.03      0.05        36
      Medium       0.00      0.00      0.00       133

    accuracy                           0.96      4100
   macro avg       0.40      0.34      0.34      4100
weighted avg       0.92      0.96      0.94      4100

Regularization


Logistic Regression with L2

In [10]:
# Import necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Split the data into training, validation, and test sets (adjust the ratios as needed)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Initialize the logistic regression model with L2 regularization
logistic_regression = LogisticRegression(penalty='l2', solver='liblinear', random_state=42)

# Train the model on the training data
logistic_regression.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred = logistic_regression.predict(X_val)

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_val, y_val_pred)
print("Confusion Matrix (Validation):")
print(conf_matrix)

# Calculate validation accuracy
validation_accuracy = accuracy_score(y_val, y_val_pred)
print("Validation Accuracy:", validation_accuracy)

# Calculate classification report for validation set
validation_report = classification_report(y_val, y_val_pred)
print("Classification Report (Validation):")
print(validation_report)

# Now, you can apply the model to the test set for final evaluation
y_test_pred = logistic_regression.predict(X_test)

# Calculate test accuracy, confusion matrix, and classification report for the test set
test_accuracy = accuracy_score(y_test, y_test_pred)
print("\nTest Accuracy:", test_accuracy)

# Calculate confusion matrix for the test set
conf_matrix_test = confusion_matrix(y_test, y_test_pred)
print("\nConfusion Matrix (Test):")
print(conf_matrix_test)

# Calculate classification report for the test set
test_report = classification_report(y_test, y_test_pred)
print("\nClassification Report (Test):")
print(test_report)


Confusion Matrix (Validation):
[[5251    0    1]
 [  40    0    0]
 [ 174    0    0]]
Validation Accuracy: 0.9606659348701061
Classification Report (Validation):
              precision    recall  f1-score   support

        High       0.96      1.00      0.98      5252
         Low       0.00      0.00      0.00        40
      Medium       0.00      0.00      0.00       174

    accuracy                           0.96      5466
   macro avg       0.32      0.33      0.33      5466
weighted avg       0.92      0.96      0.94      5466


Test Accuracy: 0.9610318331503842

Confusion Matrix (Test):
[[5253    0    1]
 [  40    0    0]
 [ 172    0    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif


Classification Report (Test):
              precision    recall  f1-score   support

        High       0.96      1.00      0.98      5254
         Low       0.00      0.00      0.00        40
      Medium       0.00      0.00      0.00       172

    accuracy                           0.96      5466
   macro avg       0.32      0.33      0.33      5466
weighted avg       0.92      0.96      0.94      5466



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Logistic Regression with L1

In [12]:
# Import necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

# Split the data into training, validation, and test sets (adjust the ratios as needed)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Initialize the logistic regression model with L1 regularization
logistic_regression = LogisticRegression(penalty='l1', solver='liblinear', random_state=42)

# Train the model on the training data
logistic_regression.fit(X_train, y_train)

# Make predictions on the validation set
y_val_pred = logistic_regression.predict(X_val)

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_val, y_val_pred)
print("Confusion Matrix (Validation):")
print(conf_matrix)

# Calculate validation accuracy
validation_accuracy = accuracy_score(y_val, y_val_pred)
print("Validation Accuracy:", validation_accuracy)

# Calculate classification report for validation set
validation_report = classification_report(y_val, y_val_pred)
print("Classification Report (Validation):")
print(validation_report)

# Now, you can apply the model to the test set for final evaluation
y_test_pred = logistic_regression.predict(X_test)

# Calculate test accuracy, confusion matrix, and classification report for the test set
test_accuracy = accuracy_score(y_test, y_test_pred)
print("\nTest Accuracy:", test_accuracy)

# Calculate confusion matrix for the test set
conf_matrix_test = confusion_matrix(y_test, y_test_pred)
print("\nConfusion Matrix (Test):")
print(conf_matrix_test)

# Calculate classification report for the test set
test_report = classification_report(y_test, y_test_pred)
print("\nClassification Report (Test):")
print(test_report)


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix (Validation):
[[5252    0    0]
 [  40    0    0]
 [ 174    0    0]]
Validation Accuracy: 0.9608488840102452


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification Report (Validation):
              precision    recall  f1-score   support

        High       0.96      1.00      0.98      5252
         Low       0.00      0.00      0.00        40
      Medium       0.00      0.00      0.00       174

    accuracy                           0.96      5466
   macro avg       0.32      0.33      0.33      5466
weighted avg       0.92      0.96      0.94      5466


Test Accuracy: 0.9612147822905233

Confusion Matrix (Test):
[[5254    0    0]
 [  40    0    0]
 [ 172    0    0]]

Classification Report (Test):
              precision    recall  f1-score   support

        High       0.96      1.00      0.98      5254
         Low       0.00      0.00      0.00        40
      Medium       0.00      0.00      0.00       172

    accuracy                           0.96      5466
   macro avg       0.32      0.33      0.33      5466
weighted avg       0.92      0.96      0.94      5466



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Neural Network

In [13]:
pip install tensorflow


In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from tensorflow import keras
from tensorflow.keras import layers

# Load your dataset (replace 'your_dataset.csv' with the actual dataset file)
# Example: df = pd.read_csv('your_dataset.csv')
# Ensure that 'rating-avg' and other relevant columns are properly loaded


# Perform label encoding for the target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split the data into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Convert labels to one-hot encoding
y_train = to_categorical(y_train)
y_val = to_categorical(y_val)
y_test = to_categorical(y_test)

# Build a simple neural network model
model = keras.Sequential()
model.add(layers.Input(shape=X_train.shape[1]))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(y_train.shape[1], activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the training data with validation data
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=64)

# Make predictions on the test set
y_test_pred = model.predict(X_test)

# Convert one-hot encoded predictions back to labels
y_test_pred_labels = np.argmax(y_test_pred, axis=1)
y_test_labels = np.argmax(y_test, axis=1)

# Evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate accuracy
accuracy = accuracy_score(y_test_labels, y_test_pred_labels)
print("Accuracy:", accuracy)

# Generate classification report
class_report = classification_report(y_test_labels, y_test_pred_labels, target_names=label_encoder.classes_)
print("Classification Report:\n", class_report)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test_labels, y_test_pred_labels)
print("Confusion Matrix:\n", conf_matrix)


Epoch 1/10
299/299 [==============================] - 4s 6ms/step - loss: 1985.6625 - accuracy: 0.9122 - val_loss: 629.3129 - val_accuracy: 0.9605
Epoch 2/10
299/299 [==============================] - 1s 3ms/step - loss: 766.7396 - accuracy: 0.9192 - val_loss: 2194.9478 - val_accuracy: 0.1103
Epoch 3/10
299/299 [==============================] - 1s 2ms/step - loss: 726.0029 - accuracy: 0.9168 - val_loss: 1383.7131 - val_accuracy: 0.9605
Epoch 4/10
299/299 [==============================] - 1s 2ms/step - loss: 581.2694 - accuracy: 0.9207 - val_loss: 235.6204 - val_accuracy: 0.9605
Epoch 5/10
299/299 [==============================] - 1s 2ms/step - loss: 468.6567 - accuracy: 0.9195 - val_loss: 728.9696 - val_accuracy: 0.9605
Epoch 6/10
299/299 [==============================] - 1s 2ms/step - loss: 454.9378 - accuracy: 0.9204 - val_loss: 409.8074 - val_accuracy: 0.9605
Epoch 7/10
299/299 [==============================] - 1s 2ms/step - loss: 444.2557 - accuracy: 0.9215 - val_loss: 241.129

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
